 // VOU PUXAR QUALQUER REASTAURANTE ALEATORIO DA ARRAY DE RESTAURANTES E
 // USAR AQUI COMO  "ESSA EH A NOSSA RECOMENDACAO PARA VOCE IR CONHECER"
 // PUXAR FOTO, REVIEWS, DESCRICAO, COMENTARIOS.... ETC
 // USUARIO PODE ADICIONAR A RECOMENDACAO PARA SUA LISTA DE FAVORITOS NO
// PERFIL OU PODE NEGAR A RECOMENDACAO E ASSIM GERAR UM OUTRO RESTAURANTE ALEATORIO....

import React from 'react'

function RandomPage() {
  return (
    <div>RandomPage</div>
  )
}

export default RandomPage